require("configs/env")
require("configs/startup")
require("configs/monitor_input")
require("configs/look")
require("configs/rules")
require("configs/bk")
require("configs/keybinds")
require("configs/layout")
