hl.on("hyprland.start", function()
	hl.exec_cmd("hyprctl setcursor Kitty")
	-- hl.exec_cmd("copyq --start-server")
	-- hl.exec_cmd("xwayland-satellite")
	-- hl.exec_cmd("qs -c noctalia-shell")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("waybar")
	hl.exec_cmd("mako")
	-- hl.exec_cmd("gnome-keyring-daemon")
	-- hl.exec_cmd("hyprsunset")
	-- hl.exec_cmd("localsend --hidden")
	hl.exec_cmd("sleep 2 && warp-cli connect")
	hl.exec_cmd("copyq")
	-- hl.exec_cmd("kitty --title test -e nvim ~/Downloads/uygula")
	hl.exec_cmd("kitty --title ncspot -e ncspot")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
end)
