hl.on("hyprland.start", function()
	hl.exec_cmd("~/.config/waybar/scripts/wallcolor.sh")
	hl.exec_cmd("hyprctl setcursor FrierenBLZ")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("waybar")
	hl.exec_cmd("mako")
	hl.exec_cmd("copyq")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
end)
